# Numpy 기초

파이썬 데이터 분석의 3대 라이브러리: 
* Numpy : 배열, 행열을 다룸
* Pandas : 엑셀와 같은 데이터프레임을 다룸
* Matplotlib : 시각화

https://numpy.org/


In [0]:
# numpy 라이브러리 임포트(불러오기)
import numpy as np

In [0]:
# 2. Array 정의 및 사용하기
# 리스트와 어레이(배열)의 차이
data1 = [1,2,3,4,5]

In [0]:
data2=[1,2,3,3.5,4]

In [0]:
# Numpy를 이용하여 array 정의하기
# 2-1. 위에서 만든 python list를 이용
arr1 = np.array(data1)

In [6]:
# array의 형태(크기) 확인
arr1.shape

(5,)

In [0]:
a= np.array([[1,2,3],[1,2,3]])
print(a.shape)

(2, 3)


In [0]:
b = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(b.shape)

(3, 3)


In [0]:
# 2-2. 바로 python list를 넣어 줌으로써 만들기
arr2 = np.array([1,2,3,4,5])
print(arr2)

[1 2 3 4 5]


In [0]:
# 크기 찍어보기
arr2.shape

(5,)

In [0]:
# array의 자료형을 확인
arr2.dtype

dtype('int64')

In [0]:
arr3 = np.array(data2)
print(arr3)

[1.  2.  3.  3.5 4. ]


In [0]:
arr3.shape

(5,)

In [0]:
arr3.dtype

dtype('float64')

In [0]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [0]:
arr4.shape

(4, 3)

#### numpy shape
<pre>
numpy에서는 해당 array의 크기를 알 수 있다.
shape 을 확인함으로써 몇 개의 데이터가 있는지, 몇 차원으로 존재하는지 등을 확인할 수 있다.
위에서 arr1.shape의 결과는 (5,)으로써, 1차원의 데이터이며 총 5라는 크기를 갖고 있음을 알 수 있다.
arr4.shape의 결과는 (4,3)으로써, 2차원의 데이터이며 4*3 크기를 갖고 있는 array이다.
</pre>

#### numpy 자료형
<pre>
arr1이나 arr2는 int라는 자료형을 갖는 것에 반해 arr3는 float64라는 자료형을 갖는다.
이는 arr3 내부 데이터를 살펴보면 3.5라는 실수형 데이터를 갖기 때문임을 알 수 있다.
numpy에서 사용되는 자료형은 아래와 같다.
(자료형 뒤에 붙는 숫자는 몇 비트 크기인지를 의미한다.)

* 부호가 있는 정수 int(8, 16, 32, 64)
* 부호가 없는 정수 uint(8, 16, 32, 54)
* 실수 float(16, 32, 64, 128)
* 복소수 complex(64, 128, 256)
* 불리언 bool
* 문자열 string
* 파이썬 오브젝트 object
* 유니코드 unicode_
</pre>

#### 2-1. np.zeros(), np.ones(), np.arange() 함수
<pre>
numpy에서 array를 정의할 때 사용되는 함수들이다.
아래 실습을 통해 각각이 어떻게 다른지 살펴본다.
</pre>



In [0]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [0]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [0]:
# np.zeros() 함수는 인자로 받는 크기만큼, 모든 요소가 0인 array를 만든다.

In [0]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [0]:
# np.ones() 함수는 인자로 받는 크기만큼, 모든 요소가 1인 array를 만든다.

In [0]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
c=np.arange(2,4)
print(c)

[2 3]


In [0]:
# np.arange() 함수는 인자로 받는 값 만큼 1씩 증가하는 1차원 array를 만든다.
# 이때 하나의 인자만 입력하면 0 ~ 입력한 인자, 값 만큼의 크기를 가진다.

#### 3.Array 연산
<pre>
기본적으로 numpy 에서 연산을 할 때는 크기가 서로 동일한 array 끼리 연산이 진행된다.
이 때 같은 위치에 있는 요소들 끼리 연산이 진행된다.

In [0]:
arr1 = np.array([[1,2,3], [4,5,6]])
arr2 = np.array([[10,11,12],[13,14,15]])

In [0]:
arr1.shape

(2, 3)

In [0]:
# 3-1. array 덧셈
arr1+arr2

array([[11, 13, 15],
       [17, 19, 21]])

In [0]:
# 3-2. array 뺄셈
arr2-arr1

array([[9, 9, 9],
       [9, 9, 9]])

In [0]:
# 3-3. array 곱셈
# 주의하자.
# 행렬의 곱처럼 곱셈이 진행되는 것이 아니라 각 요소별로 곱셈이 진행된다.
arr1*arr2

array([[10, 22, 36],
       [52, 70, 90]])

In [0]:
# 3-4. array 나눗셈
arr1/arr2

array([[0.1       , 0.18181818, 0.25      ],
       [0.30769231, 0.35714286, 0.4       ]])

In [0]:
# 3-5.array의 브로드 캐스트
# 위에서는 array가 같은 크기를 가져야 서로 연산이 가능하다고 했지만,
# numpy에서는 브로드캐스트라는 기능을 제공한다.
# 브로드캐스트란, 서로 크기가 다른 array가 연산이 가능하게끔 하는 것이다.

In [8]:
print(arr1)

[1 2 3 4 5]


In [0]:
arr3 = np.array([10,11,12])
print(arr3)

[10 11 12]


In [0]:
arr1+arr3

array([[11, 13, 15],
       [14, 16, 18]])

In [0]:
arr1*arr3

array([[10, 22, 36],
       [40, 55, 72]])

In [0]:
arr1*3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [0]:
arr1**3

array([[  1,   8,  27],
       [ 64, 125, 216]])

In [0]:
# 위와 같이 서로 크기가 다른 arr1과 arr3의 연산이 가능하다.
# 연산 결과를 살펴보면 arr3이 [10,11,12] 에서 [[10,11,12],[10,11,12]]로 확장되어
# 계산되었음을 알 수 있다.
# 동일한 방식으로 하나의 array에 스칼라 연산도 가능하다.

In [0]:
# 요소에 대해 제곱처리


In [0]:
# 4. Array 인덱싱
# numpy에서 사용되는 인덱싱은 기본적으로 python 인덱싱과 동일하다.
# 이 때, python에서와 같이 1번째로 시작하는 것이 아니라 0번째로 시작 하는 것.
# 주의!

In [0]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# 0번째 인덱스 요소
arr1[0]

0

In [0]:
# 3번째 인덱스 요소
arr1[2]

2

In [0]:
# 3번째 인덱스 요소부터 8번째 인덱스 요소
arr1[2:8]

array([2, 3, 4, 5, 6, 7])

In [0]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# 물론 1차원이 아닌 그 이상의 차원에서도 인덱싱이 가능하다.
arr2 = np.array([[1,2,3],
                 [4,5,6],
                [7,8,9],
                [10,11,12]])
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
# 2차원의 array에서 인덱싱을 하기 위해서는 2개의 인자를 입력해야 한다.
arr2[0,0]

1

In [0]:
arr2[1,2]

6

In [0]:
arr2[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [0]:
# 2행의 모든 요소 꺼내기
arr2[1,:]
#arr2[1,]

array([4, 5, 6])

In [0]:
# 2행의 3번째 요소 꺼내기
arr2[1,2]

6

In [0]:
# 모든 열의 3번째 요소 꺼내기
#arr2[:2]
arr2[:,2]

array([ 3,  6,  9, 12])

In [0]:
# 5. Array boolean 인덱싱(마스크)
# 위에서 이용한 다차원의 인덱싱을 응용하여 boolean 인덱싱을 할 수 있다.
# 해당 기능은 주로 마스크라고 이야기하는데,
# boolean 인덱싱을 통해 만들어 낸 array를 통해
# 우리가 원하는 행 또는 열의 값만 뽑아낼 수 있다.
# 즉 마스크처럼 우리가 가리고 싶은 부분은 가리고, 원하는 요소만 꺼낼 수 있다.

In [0]:
names = np.array(['lee', 'park', 'kim', 'john', 'lee', 
                  'john', 'park', 'lee'])
names

array(['lee', 'park', 'kim', 'john', 'lee', 'john', 'park', 'lee'],
      dtype='<U4')

In [0]:
names.shape

(8,)

In [0]:
# 아래에서 사용되는 np.random.randn() 함수는 기대값이 0이고,
# 표준 편차가 1인 가우시안 정규분포를 따르는 난수를 발생시키는 함수이다.
# 이 외에도 0~1의 난수를 발생시키는 np.random.rand() 함수도 존재한다.
data = np.random.randn(8,4)
data

array([[-0.978421  , -1.47541129,  0.80591044, -0.79414086],
       [ 0.05151597,  0.31594191,  1.94395494, -0.11105505],
       [ 1.37757205,  1.32775333,  0.08686065,  1.79784189],
       [ 1.36641754, -0.33507882,  0.73662278, -0.84275085],
       [ 1.74912557, -1.3946663 , -1.51674747, -1.09056506],
       [ 0.4571859 ,  1.96126744, -0.45075114,  0.546145  ],
       [ 1.11207902,  0.59452523, -0.11823333, -0.65852855],
       [-0.69909163,  0.88319333,  0.2380345 , -0.61964332]])

In [0]:
data.shape

(8, 4)

In [0]:
# 위와 같은 names와 data라는 array가 있다.
# 이 때, names의 각 요소가 data의 각 행과 연결된다고 가정해보자.
# 그리고 이 때, names가 lee인 행의 data만 보고 싶을 때 다음과 같이 마스크를 사용.

In [0]:
# 요소가 lee인 항목에 대한 mask 생성
names_lee_mask = (names=='lee')
names_lee_mask

array([ True, False, False, False,  True, False, False,  True])

In [0]:
data[names_lee_mask,:]

array([[-0.978421  , -1.47541129,  0.80591044, -0.79414086],
       [ 1.74912557, -1.3946663 , -1.51674747, -1.09056506],
       [-0.69909163,  0.88319333,  0.2380345 , -0.61964332]])

In [0]:
# 위의 결과를 보면, 요소가 lee인 것은 0번째, 4번째, 7번째 이므로
# data에서 0,4,7행의 모든 요소를 꺼내와야 한다.
# 이를 위해 요소가 lee인 것에 대한 boolean 값을 가지는 mask를 만들었고,
# 마스크를 인덱싱에 응용하여 data의 0,4,7행을 꺼냈다.

In [0]:
# 요소가 kim인 행의 데이터만 꺼내기
names_kim_list = (names=='kim')
names_kim_list

array([False, False,  True, False, False, False, False, False])

In [0]:
data[names_kim_list,:]

array([[1.37757205, 1.32775333, 0.08686065, 1.79784189]])

In [0]:
# 논리 연산을 응용하여, 요소가 kim 또는 lee 인 행의 데이터만 꺼내기
data[(names=='kim') | (names=='lee'),:]

array([[-0.978421  , -1.47541129,  0.80591044, -0.79414086],
       [ 1.37757205,  1.32775333,  0.08686065,  1.79784189],
       [ 1.74912557, -1.3946663 , -1.51674747, -1.09056506],
       [-0.69909163,  0.88319333,  0.2380345 , -0.61964332]])

In [0]:
# 물론 data array 자체적으로도 마스크를 만들고, 이를 응용하여 인덱싱이 가능하다.
# data array에서 3번째 열의 값이 0보다 작은 행을 구해보자.


In [0]:
# 먼저 마스크를 만든다.
# data array에서 3번째 열이 0보다 작은 요소의 boolean 값은 다음과 같다.
data[:,2]<0

array([False, False, False, False,  True,  True,  True, False])

In [0]:
#data[mask2,:]
data[data[:,2]<0,:]

array([[ 1.74912557, -1.3946663 , -1.51674747, -1.09056506],
       [ 0.4571859 ,  1.96126744, -0.45075114,  0.546145  ],
       [ 1.11207902,  0.59452523, -0.11823333, -0.65852855]])

In [0]:
# 위에서 만든 마스크를 이용하여 0번째 열의 값이 0보다 작은 행을 구한다.


In [0]:
# 이를 통해 특정 위치에만 우리가 원하는 값을 대입할 수 있다.
# 위에서 얻은, 0번째 열의 값이 0보다 작은 행의
# 1,2번째 열의 값에 0을 대입해보자.

In [0]:
# 3번째 열의 값이 0보다 작은 행의 1,2 번째 열 값
data[data[:,2]<0, 1:3] = 0

In [0]:
data

array([[-0.978421  , -1.47541129,  0.80591044, -0.79414086],
       [ 0.05151597,  0.31594191,  1.94395494, -0.11105505],
       [ 1.37757205,  1.32775333,  0.08686065,  1.79784189],
       [ 1.36641754, -0.33507882,  0.73662278, -0.84275085],
       [ 1.74912557,  0.        ,  0.        , -1.09056506],
       [ 0.4571859 ,  0.        ,  0.        ,  0.546145  ],
       [ 1.11207902,  0.        ,  0.        , -0.65852855],
       [-0.69909163,  0.88319333,  0.2380345 , -0.61964332]])

In [0]:
# 6. Numpy 함수
# numpy에서는 array에 적용되는 다양한 함수가 있다.

In [0]:
# 6-1. 하나의 array에 적용되는 함수
arr1 = np.random.randn(5,3)
arr1

array([[-0.00235898, -0.57752214, -0.88807823],
       [ 0.74348506,  0.25509315,  0.4782099 ],
       [-0.64446058, -0.95035836,  1.63232167],
       [ 0.67351991, -1.22038159,  0.30668079],
       [ 0.09271732,  1.45635732, -0.46822602]])

In [0]:
# 각 성분의 절대값 계산하기
np.abs(arr1)

array([[0.00235898, 0.57752214, 0.88807823],
       [0.74348506, 0.25509315, 0.4782099 ],
       [0.64446058, 0.95035836, 1.63232167],
       [0.67351991, 1.22038159, 0.30668079],
       [0.09271732, 1.45635732, 0.46822602]])

In [0]:
# 각 성분의 제곱근 계산하기 ( == array ** 0.5)
np.sqrt(arr1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan,        nan,        nan],
       [0.8622558 , 0.50506747, 0.69152722],
       [       nan,        nan, 1.27762345],
       [0.82068259,        nan, 0.55378768],
       [0.30449519, 1.2067963 ,        nan]])

In [0]:
# 각 성분의 제곱 계산하기
np.square(arr1)

array([[5.56476385e-06, 3.33531821e-01, 7.88682934e-01],
       [5.52770033e-01, 6.50725132e-02, 2.28684710e-01],
       [4.15329443e-01, 9.03181004e-01, 2.66447404e+00],
       [4.53629075e-01, 1.48933122e+00, 9.40531100e-02],
       [8.59650121e-03, 2.12097663e+00, 2.19235603e-01]])

In [0]:
# 각 성분을 무리수 e의 지수로 삼은 값을 계산하기


In [0]:
# 각 성분을 자연로그, 상용로그, 밑이 2인 로그를 씌운 값을 계산하기


In [0]:
# 각 성분의 부호 계산하기(+인 경우 1, -인 경우 -1, 0인 경우 0)


In [0]:
# 각 성분의 소수 첫 번째 자리에서 올림한 값을 계산하기


In [0]:
# 각 성분의 소수 첫 번째 자리에서 내림한 값을 계산하기


In [0]:
# 각 성분이 NaN인 경우 True를, 아닌 경우 False를 반환하기
np.isnan(arr1)

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [0]:
# 각 성분이 무한대인 경우 True를, 아닌 경우 False를 반환하기


In [0]:
# 각 성분에 대해 삼각함수 값을 계산하기(cos, cosh, sin, sinh, tan, tanh)


In [0]:
# 6-2. 두 개의 array에 적용되는 함수


In [0]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기
# (dd, subtract, multiply, divide)


In [0]:
# 두 개의 array에 대해 동일한 위치의 성분끼리 비교하여 최대값 또는
# 최소값 계산하기(maximum, minimum)


In [0]:
# 6-3. 통계 함수
# 통계 함수를 통해 array의 합이나 평균 등을 구할 때,
# 추가로 axis라는 인자에 대한 값을 지정하여
# 열 또는 행의 합 또는 평균 등을 구할 수 있다.

In [0]:
# 전체 성분의 합을 계산
np.sum(arr1)

0.886999241109677

In [0]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([-1.46795934,  1.47678811,  0.03750273, -0.24018088,  1.08084862])

In [0]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([ 0.86290273, -1.03681162,  1.06090813])

In [0]:
# 전체 성분의 평균을 계산
np.mean(arr1)

0.05913328274064513

In [0]:
# 행 간의 평균을 계산


In [0]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산
# (std, var, min, max)


In [0]:
# 전체 성분의 최소값, 최대값이 위치한 인덱스를 반환
# (argmin, argmax)
np.argmin(arr1)

10

In [0]:
np.argmax(arr1)

8

In [0]:
# 맨 처음 성분부터 각 성분까지의 누적합 또는 누적곱을 계산
# (cumsum, cumprod)
np.cumsum(arr1, axis=1)

array([[-0.00235898, -0.57988111, -1.46795934],
       [ 0.74348506,  0.99857821,  1.47678811],
       [-0.64446058, -1.59481894,  0.03750273],
       [ 0.67351991, -0.54686167, -0.24018088],
       [ 0.09271732,  1.54907464,  1.08084862]])

In [0]:
# 6-4. 기타 함수

In [0]:
arr1

array([[-0.00235898, -0.57752214, -0.88807823],
       [ 0.74348506,  0.25509315,  0.4782099 ],
       [-0.64446058, -0.95035836,  1.63232167],
       [ 0.67351991, -1.22038159,  0.30668079],
       [ 0.09271732,  1.45635732, -0.46822602]])

In [0]:
# 같은 행에 대해서 오름차순으로 정렬
np.sort(arr1, axis=0)

array([[-0.64446058, -1.22038159, -0.88807823],
       [-0.00235898, -0.95035836, -0.46822602],
       [ 0.09271732, -0.57752214,  0.30668079],
       [ 0.67351991,  0.25509315,  0.4782099 ],
       [ 0.74348506,  1.45635732,  1.63232167]])

In [0]:
# 같은 행에 대해서 내림차순으로 정렬
np.sort(arr1, axis=0)[::-1]

array([[ 0.74348506,  1.45635732,  1.63232167],
       [ 0.67351991,  0.25509315,  0.4782099 ],
       [ 0.09271732, -0.57752214,  0.30668079],
       [-0.00235898, -0.95035836, -0.46822602],
       [-0.64446058, -1.22038159, -0.88807823]])

In [0]:
# 행 방향으로 오름차순으로 정렬
